version: '3.8'

services:
  proxyhub:
    build: .
    container_name: proxyhub-service
    restart: always
    ports:
      - "8000:8000"                # Web Dashboard Panel
      - "1080:1080"                # Smart SOCKS5 Gateway
      - "20000-20050:20000-20050"  # Physical multi-country dedicated port pools
    volumes:
      - ./config.json:/app/config.json
      - ./bin:/app/bin
    environment:
      - TZ=Asia/Shanghai
